import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./globalicons.css";
import { AuthProvider } from "./context/AuthContext";

const suprapower = localFont({
  src: [
    {
      path: "../public/fonts/suprapower/SuprapowerSE-Heavy.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-suprapower",
});

const programme = localFont({
  src: [
    {
      path: "../public/fonts/programme/Programme-Regular.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-programme",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${suprapower.variable} ${programme.variable}`}>
      <head></head>
      <body className="font-programme antialiased">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
